#+TITLE: CT Nutmeg Bikepacking Route

Connecticut bikepacking route

Name TBD

*WORK IN PROGRESS*, this document is going to serve as a scratchpad for a bit.

Distance: ~370mi

Climbing: ~30,000ft

Should be ~50% unpaved by distance, >50% by time.

Of the paved roads, always try to stay off major roads (state highways, etc) if possible, even if it adds distance or climbing.

Of the unpaved roads/trails, generally prefer roads or smooth singletrack. Connecticut singletrack can be pretty challenging (rocks, roots, etc). Should definitely include some, but it shouldn't be an entire sufferfest. Also, singletrack is harder to plan around time-wise in the mixed-surface bikepacking context.

The ideal bike for the route is probably a mountain bike with XC tires, but a >40mm tire gravel bike should be acceptable too.

* Process

Divide the route into sections, then route/plan each section individually.

To maximize the amount of dirt, examine a lot of the route manually using satellite images and street view. Add surface and smoothness data to relevant roads on OSM, then have a look at the big picture using the Overpass API. To minimize zig-zagging , use BRouter with a custom dirt-finding profile to smoothly connect dirt sections.

* Potential Stops

TODO OUTDATED see individual section readmes.

- New Haven (start/end)
- West Rock
- Naugatuck State Forest (Naugatuck)
- Larkin State Park Trail
- Housatonic River (River Road north of New Milford, then Schaghticoke Road north of Kent)
  - Alternatively, Steep Rock Preserve in Washington (long track along the Shepaug river)
    - Some cool backyard "heads" at 41.6325377, -73.3158346
- Macedonia Brook State Park
- Cornwall Covered Bridge
- Mount Washington State Forest (???) Maybe. Would require going into MA to loop around, unless it is just a spur
- Great Mountain Forest
- Nepaug State Forest
- Penwood State Park
- Connecticut River / Windsor Locks Canal Trail
- Tobacco/corn fields (Windsor, Somers)
- Scantic River State Park (Enfield, Somers, East Windsor)
- Shenipsit State Forest / Soapstone Mountain (Somers)
- Bigelow Hollow / Nipmuck / Yale-Myers State Forest (Union, Ashford)
- Natchaug State Forest (Eastford/Hampton)?
  - If cutting off the NE corner
- Prime gravel near Voluntown, but also adding a lot of paved miles to travel to/from there, so perhaps not:
  - Moosup Valley State Park Trail
  - Pachaug State Forest (Voluntown)
- Air Line Trail
- Salmon River State Forest / Comstock Bridge
- Shugrue Farm Reserve
- "Route 11"
  - Slightly out of the way near the center of Salem but too cool
  - Legal?
- Devil's Hopyard
  - All trails are foot traffic only (despite appearing on the CT mountain biking page?), but there's a gravel road through it E-W
- Richard H. Goodwin Trail (Eightmile River Wild & Scenic Watershed)
- https://www.youtube.com/watch?v=1iQzXB7ieoM
  - Sections in Salem, Lyme, and East Haddam:
    - Nehantic State Forest
    - Hartman Park
    - Darling Road Preserve
    - Eightmile River WMA
    - Chapal Farm / Pizzini Preserve
    - Chapal Farm / Patrell Preserve
    - Chapal Farm / Boot Rock Preserve
- Miller Farm Nature Preserve / Sheepskin Hollow Preserve
- Roaring Brook Reserve (Dam / swim spot) and/or Hatch Lot Reserve
- Gillette Castle State Park
- Chester/Hadlyme Ferry
- Cockaponset State Forest (Nutmeg Country)
- Guilford green
- West Woods? Too technical?
- Stony Creek / Shoreline Greenway Trail
- Lighthouse Point
- Shoreline

* TODO TODO

- brouter/export turn-by-turn
- brouter profile incorporate cycleway:[side]:oneway tags and driving side
- Try other profiles to discover new possible subsections (e.g. mtb-zossebart-hard)
- OSM
  + More Strava tracks / access restrictions in Pachaug State Forest (look at fairly comprehensive official map)
  + More Strava tracks in Yale Forest near Ashford
  + More Strava tracks (unblazed but ok) in Cockaponset (Chester/Lyme)
  + More Strava tracks south of Roaring Brook Preserve, close to 82, and disused trails connecting the two (started mapping it)
  + More Strava tracks near Roxbury center along river (in/around Roxbury Land Trust, Inc. (River Road) parcel)
  + Central CT near MA border...any dirt?
  + After first draft, finer alignment/surface info of the entire route
  + Continue adding walkable/mtbable Wyndham Land Trust properties
    + DONE bull hill
    + DONE cartier
    + Robbins/O’Leary/Blain Preserve
  + Add CT backpacking shelters to OSM
    + DONE Pachaug
    + DONE Cockaponset (Pattaconk Reservoir)
    + DONE Tunxis/Nepaug
    + Natchaug
    + Nipmuck/Bigelow
    + Mohawk trail (wickwire rd)? Kinda far from the route, but could be useful
  + Winchester Land Trust?

* Overpass API

https://overpass-turbo.eu/

Visualize ways with dirt or bicycle-friendliness:

#+BEGIN_SRC
[out:json][timeout:60];
// gather results
(
way["surface"="dirt"]({{bbox}});
way["surface"="compacted"]({{bbox}});
way["surface"="earth"]({{bbox}});
way["surface"="gravel"]({{bbox}});
way["surface"="grass"]({{bbox}});
way["surface"="ground"]({{bbox}});
way["surface"="unpaved"]({{bbox}});
way["surface"="fine_gravel"]({{bbox}});
way["surface"="pebblestone"]({{bbox}});
way["surface"="sand"]({{bbox}});
way["tracktype"]["tracktype"!="grade1"]({{bbox}});
way["smoothness"="bad"]({{bbox}});
way["smoothness"="very_bad"]({{bbox}});
way["smoothness"="horrible"]({{bbox}});
way["smoothness"="very_horrible"]({{bbox}});
way["smoothness"="impassable"]({{bbox}});

way["highway"="cycleway"]({{bbox}});
way["bicycle"="yes"]({{bbox}});
way["bicycle"="designated"]({{bbox}});

// OPTIONALLY (a bit generic)
way["highway"="track"]({{bbox}}); // likely to be dirt, so include all tracks
// way["highway"="path"]({{bbox}}); // likely to be dirt, but often hiking trail, which is fine in small doses
// way["highway"="footway"]({{bbox}}); // sometimes dirt, sometimes paved
);
// print results

out body;
>;
out skel qt;
#+END_SRC

Quick version for wizard:
#+BEGIN_SRC
type:way and bicycle!=no and access!=no and access!=private and ((highway=track and surface!=asphalt and surface!=paved) or ((highway=residential or highway=unclassified or highway=service or highway=cycleway) and surface!=asphalt and surface!=paved and surface=*))
#+END_SRC

* BRouter

See [[./nutmeg-brouter-profile.brf]] and [[./nutmeg-brouter-profile-2.brf]].

Also see:
- poutnikl profiles (Trekking, MTB, etc) https://github.com/poutnikl/Brouter-profiles
- Dedicated MTB profiles, especially "mtb-zossebart-hard.brf" https://github.com/zossebart/brouter-mtb

TODO OUTDATED (but reconsider)
Generator link for full route as of 2021-08-06, using the custom profile:
http://brouter.de/brouter-web/#map=11/41.4157/-72.8314/standard,HikeBike.HillShading,route-quality&lonlats=-72.925819,41.30735;-72.95637,41.316803;-72.95778,41.322186;-72.987864,41.326907;-72.991834,41.322653;-72.993593,41.318222;-73.005717,41.315499;-73.010952,41.313983;-73.015652,41.311292;-73.01784,41.302781;-73.191732,41.246903;-73.219929,41.268396;-73.476176,41.640888;-73.496132,41.663583;-73.494158,41.763181;-73.480766,41.797045;-73.451865,41.852294;-73.388672,41.871922;-73.363309,41.871606;-73.252367,41.959173;-73.113498,42.006451;-73.003893,41.934968;-72.953339,41.910332;-72.854805,41.947562;-72.402579,41.962035;-72.15786,41.958722;-71.792824,41.677273;-71.808702,41.646617;-71.881484,41.593884;-72.432089,41.41956;-72.445093,41.407394;-72.450864,41.403193;-72.464018,41.434235;-72.643996,41.40978;-72.681899,41.281482;-72.683487,41.280548;-72.690439,41.278192;-72.75713,41.26948;-72.820687,41.265324;-72.842402,41.259324;-72.925572,41.307236

TODO OUTDATED (but reconsider)
Alternative (to NW corner) as of 2021-08-06, using the custom profile:
http://brouter.de/brouter-web/#map=10/41.6631/-73.0501/standard,HikeBike.HillShading,route-quality&lonlats=-72.925808,41.307326;-72.958403,41.335141;-72.965012,41.365923;-72.963896,41.370497;-72.957824,41.377583;-72.953253,41.417212;-73.277435,41.480032;-73.281555,41.498132;-73.281898,41.500539;-73.319836,41.564344;-73.338032,41.587399;-73.355112,41.614608;-73.437939,41.612617;-73.478107,41.666885;-73.487206,41.677114;-73.493042,41.706882;-73.495107,41.770832;-73.480355,41.80126;-73.470039,41.829409;-73.445148,41.998274;-73.468151,42.042909;-73.478622,42.148383;-73.422489,42.136927;-73.39468,42.126232;-73.390045,42.099231;-73.401203,42.070562;-73.369274,42.06916;-73.352623,42.066228;-73.346272,42.038819

* Sections

Staring in New Haven (41.30733,-72.92582), going clockwise:
1. Macedonia Brook State Park (~80mi) (41.76623,-73.49493)
2. Nepaug State Forest (~62mi) (41.84531,-72.963359)
3. Nipmuck State Forest / Bigelow Hollow State Park (~78mi) (42.00922,-72.11551)
4. Gillette Castle (~90mi) (41.42235,-72.42873)
5. New Haven (~58mi) (41.30724,-72.92558)

Each section:
- Waypoints (list of coordinates for BRouter/whatever)
- BRouter profile used
- GeoJSON export (computed segments with tags + coordinates/elevation)

* Scripts

scripts/surface-analysis.js looks at the OSM tags in the BRouter geojson output and outputs detailed stats (% unpaved, etc).

scripts/combine.js combines the geojson from each section and writes a new route.gpx. It also outputs OSM ways on the route that need surface tags (route-surface-fixmes.json).

* Trail Maps

List of CT state parks and forests allowing mountain biking:
https://portal.ct.gov/NCLI/Outdoor-Activities/Mountain-Biking

"Trails and service, logging and other roads are open to non-motorized, multiple use activities (foot travel, mountain biking, equestrian) unless posted closed."

"Connecticut Blue-Blazed Hiking Trails and the National Park Service Appalachian Trail are limited to hiking except where they overlap a multiple use trail."

* Camping

TODO Provide a list/map/POIs of nearby campgrounds and backpacking campsites/shelters.

CT backpack camping areas/shelters (free / no reservation):
List: https://portal.ct.gov/DEEP/State-Parks/Camping/Backpack-Camping---CT-State-Parks-and-Forests
Map: https://portal.ct.gov/-/media/DEEP/stateparks/maps/backpacking/BackpackCampingIndexpdf.pdf

Other:
- Cockaponset State Forest has lean-tos (around Pattaconk Reservoir)

* Misc Notes

- Unfortunately it isn't possible to go anywhere in the SW and SE corners of CT without adding many paved miles.
  The Pequonnock River Trail would have been nice but would involve almost all pavement to there from New Haven (and from there to New Milford).